title: XDRT
author: XDRT/BiancaYang
description: An attempt at the truth.

url: http://xrdt.github.io
baseurl: /xrdt.github.io

footer-links:
  twitter: xdrtxrdt
  github: xrdt

plugins: [jekyll-paginate-v2]
paginate: 25
paginate_path: "/thoughts/page:num/"
